# [Обязательное] Название сайта
site_name: AZ-WIKI

# Базовый адрес сайта
site_url: https://az-wiki.github.io/

# Описание сайта. Добавляется в meta в html-заголовке каждой страницы.
site_description: Anomaly Zone WIKI - База Данных Квестов

# Автор (или авторы) сайта. Добавляется в html-заголовок каждой страницы.
site_author: Sentinel

site_dir: docs

repo_name: az-wiki/az-wiki.github.io
repo_url: https://github.com/az-wiki/az-wiki.github.io
edit_uri: ""



theme:
    name: material    
    language: ru
    static_templates:
        - 404.html
    # Don't include MkDocs' JavaScript
    include_search_page: false
    search_index_only: true

    features:
        - content.code.annotate
        - content.tabs.link
        - header.autohide
        # - navigation.expand
        # - navigation.indexes
        # - navigation.instant
        - navigation.sections
        - navigation.tabs
        # - navigation.tabs.sticky
        - navigation.top
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
        # - toc.integrate
    palette:
        - scheme: default
          primary: indigo
          accent: indigo
          toggle:
            icon: material/toggle-switch-off-outline
            name: "Сменить Тему на: Тёмную"
        - scheme: slate
          primary: black
          accent: black
          toggle:
            icon: material/toggle-switch
            name: "Сменить Тему на: Светлую"
    font:
      text: Roboto
      code: Roboto Mono
    favicon: assets/favicon.png
    icon:
      logo: material/book-account

# Extras
extra:
  disqus: ""
  social:
    - icon: fontawesome/brands/vk
      link: https://vk.com/kick_me_plz/
  homepage: https://az-wiki.github.io/
  alternate:
    # Switch to Russian
    - name: Русский
      link: https://az-wiki.github.io/
      lang: ru
      
    # Switch to English
    - name: English
      link: https://az-wiki.github.io/en/
      lang: en

# Extensions
markdown_extensions:
  - admonition
  - meta
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - toc:
      permalink: true


# Структура навигации генерируемого сайта.
nav:
    - Главная: index.md
    - Квесты:
        - База Данных: quests/all/index.md
    - Квесты (по локациям):
        - Любеч(Вокзал): quests/q-lubech.md
        - Любеч(Окрестности): quests/q-lubech-okr.md
        - Везувий: quests/vez.md
        - Новая Земля: quests/nz.md
        - Тунгуска: quests/tunga.md
        - Караван: quests/karavan.md
        - Болото Василисков: quests/bv.md
        - Пустошь: quests/pust.md
    - Персонажи:
        - Любеч(Вокзал): pers/lubech/index.md
        - Любеч(Окрестности): pers/okrestnosti/index.md
        - Везувий: pers/vezuvii/index.md
        - Новая Земля: pers/novaya/index.md
        - Тунгуска: pers/tunguska/index.md
        - Караван: pers/karavan/index.md
        - Болото Василисков: pers/boloto/index.md
        - Пустошь: pers/pustosh/index.md
    - Обновление: news.md
    - FAQ: faq.md
    - Инфо:
        - Связь: about/links.md
        - Благодарность: about/thanks.md



extra_css:
    - css/extra.css

copyright: Copyright &copy; 2021 <a href="https://vk.com/kick_me_plz">Alexander Ramazanov</a>.

# Список использованных плагинов MkDocs
plugins:
    - search:
        lang:
            - en
            - ru
    - git-revision-date-localized
#        type: timeago
#        timezone: Moscow
#        locale: ru
#        fallback_to_build_date: false
#        enable_creation_date: true
    - section-index
    - autorefs
